### ISSUE TITLE
Ensure yaml file in ASpace test matches ASpace prod

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#106]
The current yaml file from prod is posted in basecamp at the end of the thread here: https://3.basecamp.com/3410311/buckets/29543127/messages/5833055791#__recording_5922785004
- [ ] Check existing prod yaml file against the yaml file in ASpace test to ensure they match and all user-defined fields are represented in the test yaml file.  I believe that we only have user_defined fields within accessions currently, but please report in comments below what those are and if you find others.

If configured correctly, the ASpace test display should match that in prod:
![Screen Shot 2023-03-13 at 11.44.34 AM.png](https://images.zenhubusercontent.com/62ff941ccf40d827200a9edf/48c74520-fad4-4c46-be67-f26ecb4a70ac)

More documentation about user-defined fields is available here: 
Resources: https://archivesspace.atlassian.net/wiki/spaces/ArchivesSpaceUserManual/pages/895812108/User+Defined+Fields+-+Resources
Accessions: https://archivesspace.atlassian.net/wiki/spaces/ArchivesSpaceUserManual/pages/893976727/User+Defined+Fields+-+Accessions

**Comment by erussey** [comment]
This is a task that is something that will need to be supported once the system is operationalized, so it would help to determine who is equipped to do this work going forward and assign the ticket to that group.

**Comment by bwatson78** [comment]
The quickest way to ensure they both match is to place the associated values passed along by Blake into our plugin. PR made: https://github.com/emory-libraries/aspace_static_plugins/pull/40

**Comment by erussey** [comment]
Some configuration is still missing here.  In test I'm seeing all the possible user defined fields rather than just the user defined fields that we have configured.  Compare screenshot above from prod with this one from test:
![Screen Shot 2023-03-21 at 8.25.39 AM.png](https://images.zenhubusercontent.com/62ff941ccf40d827200a9edf/1b131426-137c-4fba-900f-8d4e03b91fd0)

**Comment by erussey** [comment]
Note that in the documentation, it covers how to remove the fields/labels we aren't using from the UI: https://archivesspace.atlassian.net/wiki/spaces/ArchivesSpaceUserManual/pages/895812108/User+Defined+Fields+-+Resources (see near bottom of the page) .  I am unsure if we can make certain fields appear in the resource only and others in the accession only.  Probably a question for Blake.

**Comment by bwatson78** [comment]
@erussey The change that I've made is to include the exact state of the en.yml that Blake passed to us with the addition of of string_2 setter
```
en:
  accession:
    user_defined: 
      real_1: Appraised value
      real_2: Purchase price
      date_1: Appraisal date
      date_1_inline_help: e.g. YYYY-MM-DD
      enum_1: Purchase price currency
  resource:
    user_defined: 
      real_1: Appraised value
      real_2: Purchase price
      date_1: Appraisal date
      date_1_inline_help: e.g. YYYY-MM-DD
      enum_1: Purchase price currency
      string_2: MMS ID
  digital_object:
    user_defined: 
      real_1: Appraised value
      real_2: Purchase price
      date_1: Appraisal date
      date_1_inline_help: e.g. YYYY-MM-DD
      enum_1: Purchase price currency
  user_defined: &user_defined_attributes
    real_1: Appraised value
    real_2: Purchase price
    date_1: Appraisal date
    date_1_inline_help: e.g. YYYY-MM-DD
    enum_1: Purchase price currency
```
From the tutorial you listed, it explicitly calls out `To edit user-defined fields, the en.yml file in which the translation values are encoded needs to be edited on your server If you have access to the system files for your ArchivesSpace installation, you can edit these values. If not, talk to your system administrator.`

It seems attempting to edit those from the plugins side isn't producing our desired results. It seems our options are to, first, revert the changes on our plugin side, and, second, either request the ability to ssh into both servers (I'm guessing they wouldn't like that) or ask Lyrasis to make the changes on their side.
