### ISSUE TITLE
Add a user defined field in Aspace for MMS id

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#111]
- [ ] Add a user-defined field for the Alma MMS ID number in the resource record (collection level record).  To do so: add a line for "string_2: Alma MMS ID" under resource: -> user_defined: in the YAML file

Please be sure a human readable label is included in the staff side UI display for the resource record.  

See more about user defined fields in the ASpace manual: https://archivesspace.atlassian.net/wiki/spaces/ArchivesSpaceUserManual/pages/909934631/ArchivesSpace+User+Manual

**Comment by rotated8** [comment]
This goes in the same file as #106

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/aspace_static_plugins/pull/40

**Comment by erussey** [comment]
Similar to #106, I'd like to see only the user defined fields that apply to resources.  We should only see Alma MMS ID as the field label (note in the screenshot it reads just MMS ID" and only that option under the user defined fields.  Right now it's pulling in all user defined fields for both resources and accession records + non-configured user defined fields.  
![Screen Shot 2023-03-21 at 8.27.09 AM.png](https://images.zenhubusercontent.com/62ff941ccf40d827200a9edf/fc2e3fee-0eba-4ac5-821f-c0c5bfd04395)

**Comment by bwatson78** [comment]
@erussey The change that I've made is to include the exact state of the en.yml that Blake passed to us with the addition of of string_2 setter
```
en:
  accession:
    user_defined: 
      real_1: Appraised value
      real_2: Purchase price
      date_1: Appraisal date
      date_1_inline_help: e.g. YYYY-MM-DD
      enum_1: Purchase price currency
  resource:
    user_defined: 
      real_1: Appraised value
      real_2: Purchase price
      date_1: Appraisal date
      date_1_inline_help: e.g. YYYY-MM-DD
      enum_1: Purchase price currency
      string_2: MMS ID
  digital_object:
    user_defined: 
      real_1: Appraised value
      real_2: Purchase price
      date_1: Appraisal date
      date_1_inline_help: e.g. YYYY-MM-DD
      enum_1: Purchase price currency
  user_defined: &user_defined_attributes
    real_1: Appraised value
    real_2: Purchase price
    date_1: Appraisal date
    date_1_inline_help: e.g. YYYY-MM-DD
    enum_1: Purchase price currency
```
From the tutorial you listed, it explicitly calls out `To edit user-defined fields, the en.yml file in which the translation values are encoded needs to be edited on your server If you have access to the system files for your ArchivesSpace installation, you can edit these values. If not, talk to your system administrator.`

It seems attempting to edit those from the plugins side isn't producing our desired results. It seems our options are to, first, revert the changes on our plugin side, and, second, either request the ability to ssh into both servers (I'm guessing they wouldn't like that) or ask Lyrasis to make the changes on their side.
